version: '3'

services: 
  app:
    build: ./build
    container_name: productserver
    ports:
      - "9000:9000"
    volumes: 
      - .:/go/src

  db:
    image: postgres:13.3
    restart: always
    tty: true
    volumes:
      - .pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=products
    ports:
      - "5432:5432"